baseurl = "https://opensourcefoundries.com/"
title = "Open Source Foundries, Ltd."
theme = "universal"
publishDir = "../docs"
languageCode = "en-us"
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"
# Enable comments by entering your Disqus shortname
disqusShortname = "osfoundries"
# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-111281311-1"

# Define the number of posts per page
paginate = 10

[menu]
[[menu.main]]
    name = "Product"
    url  = "/product/"
    weight = 1
    [[menu.main]]
        name = "Overview"
        parent = "Product"
        url  = "/product/#overview"
        weight = 1
    [[menu.main]]
        name = "Linux microPlatform"
        parent = "Product"
        url  = "/product/#linux-microPlatform"
        weight = 2
    [[menu.main]]
        name = "Zephyr microPlatform"
        parent = "Product"
        url  = "/product/#zephyr-microPlatform"
        weight = 3
    [[menu.main]]
        name = "Lifetime Support"
        parent = "Product"
        url  = "/product/#lifetime-Support"
        weight = 4
    [[menu.main]]
        name = "Hardware"
        parent = "Product"
        url  = "/product/#hardware"
        weight = 5
    [[menu.main]]
        name = "Pricing"
        parent = "Product"
        url  = "/product/#pricing"
        weight = 5
[[menu.main]]
    name = "Partners"
    url  = "/partners/"
    weight = 2
[[menu.main]]
    name = "Blog"
    url  = "/blog/"
    weight = 3
[[menu.main]]
    name = "About"
    identifier = "About"
    url  = "/about/"
    weight = 4
    [[menu.main]]
        name = "Company"
        parent = "About"
        url  = "/about/#Company"
        weight = 1
    [[menu.main]]
        name = "Investors"
        parent = "About"
        url  = "/about/#Investors"
        weight = 2
    [[menu.main]]
        name = "Team"
        parent = "About"
        url  = "/about/#Team"
        weight = 3
    [[menu.main]]
        name = "Community"
        parent = "About"
        url  = "/about/#Community"
        weight = 4
    [[menu.main]]
        name = "Careers"
        parent = "About"
        url  = "/about/#Careers"
        weight = 5
    [[menu.main]]
        name = "Labs"
        parent = "About"
        url  = "/labs"
        weight = 5


[[menu.main]]
    name = "Getting Started"
    url  = "https://app.foundries.io"
    weight = 99

[[menu.topbar]]
    weight = 1
    name = "GitHub"
    url = "https://github.com/opensourcefoundries"
    pre = "<i class='fa fa-2x fa-github'></i>"

[[menu.topbar]]
    weight = 2
    name = "Facebook"
    url = "https://www.facebook.com/osfoundries"
    pre = "<i class='fa fa-2x fa-facebook'></i>"

[[menu.topbar]]
    weight = 3
    name = "Twitter"
    url = "https://twitter.com/osfoundries"
    pre = "<i class='fa fa-2x fa-twitter'></i>"

[[menu.topbar]]
    weight = 4
    name = "Email"
    url = "mailto:support@opensourcefoundries.com"
    pre = "<i class='fa fa-2x fa-envelope'></i>"



[params]
    viewMorePostLink = "/blog/"
    author = "DevCows"
    defaultKeywords = ["microPlatform", "osf", "updates"]
    defaultDescription = ""

    # Google Maps API key (if not set will default to not passing a key.)
    #googleMapsApiKey = "AIzaSyCFhtWLJcE30xOAjcbSFi-0fnoVmQZPb1Y"

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "default"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    #
    # Enable the contact form by entering your Formspree.io email
    email = "contact@opensourcefoundries.com"
    career_email = "careers@opensourcefoundries.com"
    about_us = """<p>We provide best-in-class software platforms with lifetime support for
    building and maintaining connected products, ranging from the smallest sensors to
    smart and edge devices. Our core products are Zephyr RTOS and Linux based microPlatforms,
    which provide product quality templates to build secure, OTA updatable, connected devices
    for industrial and consumer markets.</p>"""
    copyright = "Copyright 2018 Open Source Foundries Ltd. All rights reserved."

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    logo = "img/logo.png"
    address = """<p><strong>Open Source Foundries Ltd.</strong>
        <br>Cambridge, UK
        <br><br><strong>Open Source Foundries Inc.</strong>
        <br>Boulder CO, USA
      </p>
      """
    latitude = "-12.043333"
    longitude = "-77.028333"

[Permalinks]
    blog = "/blog/:year/:month/:day/:filename/"

# Enable or disable top bar with social icons
[params.topbar]
    enable = true
    text = ""

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = true

[params.front]
    enable = true
    title = "Title"
    description = "description"

[params.carousel]
    enable = false
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more informtion take a look at the README.

[params.pillars]
    enable = true

[params.partners]
    enable = true

[params.overview]
    enable = true

[params.signup]
    enable = true

[params.features]
    enable = false
    # All features are defined in their own files. You can find example items
    # at 'exampleSite/data/features'.
    # For more informtion take a look at the README.

[params.technologies]
    enable = false
    # All technologies are defined in their own files. You can find example items
    # at 'exampleSite/data/technologies'.
    # For more informtion take a look at the README.
    title = "Technologies"
    subtitle = "Use the latest technologies to develop a better product faster"

[params.testimonials]
    enable = false
    # All testimonials are defined in their own files. You can find example items
    # at 'exampleSite/data/testimonials'.
    # For more informtion take a look at the README.
    title = "Testimonials"
    subtitle = "We have worked with many clients and we always like to hear they come out from the cooperation happy and satisfied. Have a look what our clients said about us."

[params.see_more]
    enable = false
    icon = "fa fa-file-code-o"
    title = "Do you want to see more?"
    subtitle = "We have prepared for you more than 40 different HTML pages, including 5 variations of homepage."
    link_url = "#"
    link_text = "Check other homepages"

[params.clients]
    enable = false
    # All clients are defined in their own files. You can find example items
    # at 'exampleSite/data/clients'.
    # For more informtion take a look at the README.
    title = "Our Partners"
    subtitle = "We have proudly collaborated with the following companies."

[params.get_started]
    enable = false
    title = "Get Started"
    subtitle = "We provide the software for your connected IoT products and allow you to get started with a free trial subscription to the update service"

[params.recent_posts]
    enable = false
    title = "From our blog"
    subtitle = ""
